export const ACTION_START = 'ACTION_START';
export const ACTION_SUCCESS = 'ACTION_SUCCESS';
export const ACTION_FAILED = 'ACTION_FAILED';
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCCESS';
/*export const AUTH_VERIFY_EMAIL = 'AUTH_VERIFY_EMAIL'
export const AUTH_ACCOUNT_CREATE_SUCCESS  ='AUTH_ACCOUNT_CREATE_SUCCESS'
export const AUTH_RESEND_SUCCESS = 'AUTH_RESEND_SUCCESS'*/